/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import sedec2.arib.extractor.TlvDemultiplexer;

import static org.junit.Assert.*;

public class SedecTest {
    @Test public void testPut() {
        assertTrue("put of TlvDemultiplexer instance should return 'true'", 
                new TlvDemultiplexer().put(new byte[]{0x01, 0x02}));
    }
}
